### ISSUE TITLE
Specified Path via `dest` property is ignored

### ISSUE THREAD

**Issue by alexanderniebuhr** [crowdin/vscode-crowdin#56]
**Describe the bug**
According to the documentation for the configuration file (https://support.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type).
Setting `dest` property to files array object should upload the files to the specified path. However this setting seems to be ignored using the VS Code Extension. (Using the CLI with the same project, works)

**To Reproduce**
```yml
# crowdin.yml
"project_id": "XYZ"
"api_token": "XYZ"
"preserve_hierarchy": true

"files": [
  {
    "source": "/locales/de-DE.json",
    "dest": "/skeleton/de-DE.json",
    "translation": "/locales/%locale%.json",
  }
]
```

**Expected behavior**
I expect that VS Code Extension behaves 1:1 with the CLI.

**Screenshots**

**Environment (please complete the following information):**
  System:
    OS: Windows 10 10.0.22478
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
    Memory: 16.20 GB / 31.92 GB
  Binaries:
    Node: 16.11.0 - ~\AppData\Local\Volta\tools\image\node\16.11.0\node.EXE
    Yarn: 1.22.11 - ~\AppData\Local\Volta\tools\image\yarn\1.22.11\bin\yarn.CMD
    npm: 8.0.0 - ~\AppData\Local\Volta\tools\image\npm\8.0.0\bin\npm.CMD
  Utilities:
    Git: 2.33.1.
  Virtualization:
    Docker: 20.10.9 - C:\docker\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Visual Studio: 16.7.30621.155 (Visual Studio Community 2019)
  Languages:
    Bash: 4.4.12 - C:\Windows\System32\bash.EXE
    Go: 1.16 - C:\Program Files\Go\bin\go.EXE
    Java: 14.0.2
    Python: 3.9.7
    Python3: 3.9.7
  Browsers:
    Edge: Spartan (44.22478.1012.0), Chromium (94.0.992.50), ChromiumDev (96.0.1047.2)
    Internet Explorer: 11.0.22478.1000
  Monorepos:
    Yarn Workspaces: 1.22.11

**Additional context**
Not quite sure if that is a bug in vscode-crowdin or the used api client (https://github.com/crowdin/crowdin-api-client-js)
