### ISSUE TITLE
Unable to download Translation

### ISSUE THREAD

**Issue by taooceros** [crowdin/vscode-crowdin#58]
**Describe the bug**
Unable to download Translation

**To Reproduce**
```yaml
files:
  [
    {
      source: Languages/en.xaml,
      translation: /%original_path%/%two_letters_code%.xaml,
    },
    {
      source: Properties/Resources.resx,
      translation: /%original_path%/Resources.%locale%.resx,
    },
  ]
commit_message: "[ci skip]"
project_id: "482461"
``` 
(api key is deleted here)

**Expected behavior**
It download translation files.

**Screenshots**
![image](https://user-images.githubusercontent.com/45326534/146623263-738b3eb4-0b82-43e9-92aa-46b8bc39d5d8.png)

**Environment (please complete the following information):**
 - OS: Windows
 - VS Code version 1.64 Insider

**Additional context**
