### ISSUE TITLE
No translations files

### ISSUE THREAD

**Issue by Justman10000** [crowdin/vscode-crowdin#65]
**Describe the bug**
Translation files are not loaded

**To Reproduce**
1. `crowdin.yaml` configuration file
2. Go to **Crowdin Explorer**
3. Click on the dropdown arrow to load translations
4. See nothing

**Expected behavior**
The translations are displayed

**Environment (please complete the following information):**
 - OS: Microsoft Windows 11
 - VS Code version: 1.66

**Comment by andrii-bodnar** [comment]
Hi @Justman10000!

Could you please provide your `crowdin.yml` configuration file? Without credentials, of course

**Comment by Justman10000** [comment]
> Hi @Justman10000!
> 
> Could you please provide your `crowdin.yml` configuration file? Without credentials, of course

```yml
"project_id": "id"
"api_token": "my_token"

"files": [
  {
    "source": "sources/**/*.xml",
    "translation": "translations/%two_letters_code%/%original_file_name%"
  }
]
```

**Comment by andrii-bodnar** [comment]
@Justman10000, thank you!

Are there any notifications from the VS Code after clicking the translations download button?

Also, please check the [resulting file after translations export](https://support.crowdin.com/files-management/#file-settings) configuration for your Crowdin files - I should be the same as your `translation` pattern in the `crowdin.yml` configuration file.

**Comment by Justman10000** [comment]
> @Justman10000, thank you!
> 
> Are there any notifications from the VS Code after clicking the translations download button?

No, VS Code doesn't output anything, it seems to be downloaded but I don't see any files!

**Comment by andrii-bodnar** [comment]
@Justman10000 please check your [resulting file after translations export](https://support.crowdin.com/files-management/#file-settings) if it's the same as the `translation` pattern in the `crowdin.yml` file

**Comment by andrii-bodnar** [comment]
@Justman10000 any updates? Is this issue still relevant?

**Comment by Justman10000** [comment]
> @Justman10000 any updates? Is this issue still relevant?

I do not get it!

**Comment by Justman10000** [comment]
I now have this:

```yml
"files": [
  {
    "source": "sources/**/*.csv",
    "translation": "/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",
  }
]
```

**Comment by Justman10000** [comment]
What has to go in _source_ and what in _translation_?

**Comment by andrii-bodnar** [comment]
@Justman10000 

`source` - pattern to match local source files in your project (only for the source language)

`translation` - pattern to specify where translations are stored

For more details please read the [Writing a Simple Configuration File](https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file)

**For example**:

```
project
│
└───en
│   │   file011.xml
│   │   file012.xml
│   
└───uk
    │   file001.xml
    │   file012.xml
...
```

For the files structure above config should look like this:

```json
"files": [
  {
    "source": "en/*.xml",
    "translation": "/%two_letters_code%/%original_file_name%",
  }
]
```

**Comment by Justman10000** [comment]
How do I load the files now?

**Comment by andrii-bodnar** [comment]
@Justman10000 please describe in more detail what is your source and translation files structure and the actions you are trying to do, step by step.

Thank you.

**Comment by Justman10000** [comment]
> @Justman10000 please describe in more detail what is your source and translation files structure and the actions you are trying to do, step by step.
> 
> Thank you.

Exactly, I don't know how these are structured! I work for WeMod, among others, as a manager, but I don't know how the structure of the files is built there because the GitHub repository is not public!

**Comment by andrii-bodnar** [comment]
@Justman10000 please share your Crowdin project ID. You can share it here or using [this](https://crowdin.com/contacts) form with specifying the link to this issue.

**Comment by Justman10000** [comment]
> @Justman10000 please share your Crowdin project ID. You can share it here or using [this](https://crowdin.com/contacts) form with specifying the link to this issue.

What for?

**Comment by Justman10000** [comment]
So, I now have this:

```yml
"project_id": "453344"
"api_token": "d1ab45d37899e4893f7aca0bede66e194dbdcec9db2370a16254ddb7b200132a344c015b6ace2f5a"

"files": [
  {
    "source": "https://github.com/flarum/docs/tree/master/i18n/en/*.json",
    "translation": "/master/i18n/%two_letters_code%/%original_file_name%",
  },
  {
    "source": "https://github.com/flarum/docs/tree/master/i18n/en/*/*.json",
    "translation": "/master/i18n/%two_letters_code%/%original_path%/%original_file_name%"
  }
]
```

However, I only get this:

> Failed to download translations for project 453344. Forbidden
