### ISSUE TITLE
Translations don't get downloaded with `three_letters_code` is in `files.translations`

### ISSUE THREAD

**Issue by akamfoad** [crowdin/vscode-crowdin#75]
**Describe the bug**
When I have `three_letters_code` in my `files.translation`, and click on download translations, the UI shows loading infinitely, but when I use `two_letters_code` it'll get it without a problem.

**To Reproduce**
1. Create a `crowdin.yaml` configuration file and specify `three_letters_code` in translations.
2. Go to `Crowdin` extension
3. Click on `Download Translations` button in **TMS FILES** section
4. See the loading goes infinitely and never ends, also the files never show up.

**Expected behavior**

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.73.1

**Additional context**
Here is my `crowding.yml`:

```yml
"project_id": "MY_PROJECTID"
"api_token": "MY_API_TOKEN"
"base_path": "/public/locales/"
"branch": "main"
"files":
  [
    {
      "source": "/en/**/*.json",
      "translation": "/%two_letters_code%/%original_file_name%",
    },
  ]
```
